dynamic-datasource:
  beijing:
    password: root
    url: jdbc:mysql://localhost:3306/testdemo
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  shenzhen:
    password: root
    url: jdbc:mysql://localhost:3306/testdemo2
    username: root
    driver-class-name: com.mysql.jdbc.Driver
logging:
#  config: classpath:log.yml
  level:
    com:
      jql:
        springboot:
          dynamicdatasource:
            mapper: dubug

mybatis:
  # spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


